am_ru_converter/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'', include(('converter.urls', 'converter'), namespace='converter')),

]

converter/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),

]

converter/models.py
from django.db import models

# Create your models here.

converter/forms.py
from django import forms

class MainForm(forms.Form):
    class Meta:
        fields = ['recipe']
        # widgets = {'text': forms.Textarea(attrs={'id': 'textarea-source'})}

    recipe = forms.CharField(label='', widget=forms.Textarea())

converter/views.py
from django.shortcuts import render
from . import forms
from .my_converter.converter import ARConverter
from googletrans import Translator


# Create your views here.

def index(request):
    conv_recipe = 'Перевод'
    English = True

    if request.method != 'POST':
        form = forms.MainForm()


    else:
        form = forms.MainForm(request.POST)

        if form.is_valid():

            converter = ARConverter()
            text = form.cleaned_data['recipe']
            conv_recipe = ''
            for line in text.split('\n'):
                conv_recipe += converter.process_line(line) + '\n'

            to_translate = request.POST.get('to_translate')
            if to_translate == 'RU':
                English = False
                translator = Translator(service_urls=[
                'translate.google.com',
                'translate.google.co.kr',                ])
                translation = translator.translate(conv_recipe, dest='ru')
                conv_recipe = translation.text


    context = {'form': form, 'translation': conv_recipe, 'En': English}

    return render(request, 'converter/index.html', context)

converter/templates/converter/index.html
{% load bootstrap3 %}

<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <title>Am-Ru converter</title>
    {% bootstrap_css %}
    <link href="https://fonts.googleapis.com/css?family=Poiret+One&display=swap" rel="stylesheet">

    <style>


        textarea.form-control {
            min-width: 100%;
            max-width: 100%;
            border: none;
            box-shadow: none;
            height: 100%;
            background: #fffdf8;

        }

        h4{
            text-align: center;
        }

        body {
            font-family: 'Roboto Slab', sans-serif;
            color: #555;
            background: #fff7da2b;
        }

        .header{
            font-family: 'Poiret One', cursive;
            text-transform: uppercase;
            font-size: 23px;
            text-align: center;
            font-weight: bold;
            letter-spacing: 1px;
            margin-top: 3%;
            margin-bottom: 2%;

        }

        .col-header {
            padding: 5%;
            background-color: #cccccc21;
            margin: 0;
            margin-bottom: 20px;
            letter-spacing: 2px;
            font-size: 23px;
            color: #333;

        }

        .main-container {
            padding-top: 15px;
            display: flex;
            flex-wrap: wrap;
            box-shadow: 0 0 10px rgb(227, 227, 227);
            margin-bottom: 10px;
        }

        .has-success .form-control,
        .has-success .form-control:focus,
        .form-control:focus {
            border: none;
            outline: 0;
            -webkit-box-shadow: none;
           box-shadow:none;
        }

        .my-column {
            padding: 0;
            padding-left: 15px;
            display: flex;
            flex-direction: column;

        }

        .right-column{
            padding-right: 15px;
        }

        .my-column p {
            padding-left: 15px;
            margin-bottom: 25px;

        }

        .my-column > .form-group {
            height: 100%;
        }

        .my-btn{
        margin-top: 10px;
        padding: 1%;
        background-color: #3B283B;
        border-color: #280848;
        font-size: 21px;
        }

       .btn-primary:active:focus, .btn-primary:active,
       .btn-primary .focus, .btn-primary:focus,
       .btn-primary:hover {
         color: #fff;
         background-color: #512857;
         border-color: #400330;
        }

        .form-check-label{
            font-weight: normal;
        }

    </style>
</head>
<body>
    <div class="container">
        <h1 class="header   ">Конвертер рецептов из американской системы счисления в граммы</h1>
        <hr style="width: 300px; margin-bottom: 30px;"/>
        <div>
            <form name="sourceForm" action="{% url 'converter:index'%}" method = POST>
                {% csrf_token %}

                <div class="row main-container">
                    <div class="col-md-6 col-sm-6 col-xs-12 my-column">
                        <h4 class="col-header">Американская</h4>
                        {% bootstrap_form form %}

                    </div>
                    <div class="col-md-6 col-sm-6 col-xs-12 my-column right-column">
                         <h4 class="col-header">Метрическая</h4>
                        {{translation|linebreaks}}
                    </div>
                 </div>
                <div class="row">
                    <div class="form-check form-check-inline col-md-6 col-sm-6 col-xs-12">
                      <input class="form-check-input" type="radio" name="to_translate" id="inlineRadio1" value="EN" {% if En %} checked{% endif %}>
                      <label class="form-check-label" for="inlineRadio1">Оставить на английском</label>
                    </div>
                    <div class="form-check form-check-inline col-md-6 col-sm-6 col-xs-12">
                      <input class="form-check-input" type="radio" name="to_translate" id="inlineRadio2" value="RU" {% if not En %} checked{% endif %}>
                      <label class="form-check-label" for="inlineRadio2">Перевести на русский</label>
                    </div>
                </div>
                    <div class="row">
                        <div class="col-md-12">
                                <button class="btn btn-primary btn-block my-btn" type="submit">Сотвори чудо! </button>
                        </div>

                    </div>
                <div style="margin-top: 10px; margin-bottom: 10px; text-align: right;">
                    Сообщить о неисправности: <a href="mailto:anevolina@pm.me">anevolina@pm.me</a>
                </div>

        </form>

    </div>
    {% bootstrap_javascript %}
    <script>
        function attachSubmitByPaste() {
            const textarea = document.getElementById('id_recipe');
            textarea.addEventListener('paste', function() {
                // let's wait for the value updated in textarea first
                setTimeout(() => {
                    document.sourceForm.submit();
                }, 0);

            })
        }

        attachSubmitByPaste();
    </script>
</body>
</html>